//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkgMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using System.Data;
    using System.Data.Entity;
    using System.ComponentModel.DataAnnotations;

    public partial class balance : Statechart
    {
        public long operation_id { get; set; }
        public string Type_Operation { get; set; }
        public decimal Sum { get; set; }
        public decimal BalanceAfterOperation { get; set; }
        public string Login { get; set; }
        public string Description { get; set; }
        public string DateOperation { get; set; }
        public virtual usr usr { get; set; }



        MyParkingEntities mp = new MyParkingEntities();
        public bool Operation(string Type_Operation, decimal price, decimal BalanceAfterOperation,string Login, string Description,string Date)
        {
            bool Result = true;
            try
            {
                balance bl = new balance();
                bl.Type_Operation = Type_Operation;
                bl.Sum = price;
                bl.BalanceAfterOperation = BalanceAfterOperation;
                bl.Login = Login;
                bl.Description = Description;
                bl.DateOperation = Date;
                bl.Status = "True";
                mp.balance.Add(bl);
                mp.SaveChanges();
                Result = true;
            }
            catch
            {
                Result = false;
            }
            return Result;
        }
    }
}
