//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkgMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class levelzone
    {
        public levelzone()
        {
            this.place = new HashSet<place>();
        }
    
        public long id_location_level { get; set; }
        public int Parking_zone { get; set; }
        public int Level { get; set; }
        public string TypeLevel { get; set; }
    
        public virtual parkingzone parkingzone { get; set; }
        public virtual ICollection<place> place { get; set; }
    }
}
