//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkgMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyParkingEntities : DbContext
    {
        public MyParkingEntities()
            : base("name=MyParkingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<balance> balance { get; set; }
        public DbSet<levelzone> levelzone { get; set; }
        public DbSet<parkingzone> parkingzone { get; set; }
        public DbSet<place> place { get; set; }
        public DbSet<reservation> reservation { get; set; }
        public DbSet<reservation_tariff> reservation_tariff { get; set; }
        public DbSet<tariffonabonementforvisit> tariffonabonementforvisit { get; set; }
        public DbSet<tariffonplace> tariffonplace { get; set; }
        public DbSet<ts> ts { get; set; }
        public DbSet<type_parking> type_parking { get; set; }
        public DbSet<usingtariffonabonementforvisit> usingtariffonabonementforvisit { get; set; }
        public DbSet<usr> usr { get; set; }
        public DbSet<visit> visit { get; set; }
        public DbSet<visitparameters> visitparameters { get; set; }
    }
}
