//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkgMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class parkingzone
    {
        public parkingzone()
        {
            this.levelzone = new HashSet<levelzone>();
        }
    
        public int Parking_zone { get; set; }
        public long id_type { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<levelzone> levelzone { get; set; }
        public virtual type_parking type_parking { get; set; }
    }
}
