//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkgMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservation_tariff : TariffPlan
    {
        public reservation_tariff()
        {
            this.reservation = new HashSet<reservation>();
        }
    
        public long id_Reservation_Tariff { get; set; }
        public int FirstFreeTimeInMinutes { get; set; }
        public decimal PriceInRubForHourHightFreeTime { get; set; }
        public int ValidityPeriodFromTheTimeOfActivationInHour { get; set; }
    
        public virtual ICollection<reservation> reservation { get; set; }
    }
}
