//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkgMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tariffonplace : TariffPlan
    {
        public tariffonplace()
        {
            this.place = new HashSet<place>();
        }
    
        public long id_tariff_on_place { get; set; }
        public string SupportClimateControl { get; set; }
        public string Type { get; set; }
        public decimal PriceForHourWithoutAbonement { get; set; }
        public decimal PriceForHourWithAbonement { get; set; }
    
        public virtual ICollection<place> place { get; set; }
    }
}
