//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkgMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tariffonabonementforvisit : TariffPlan
    {
        public tariffonabonementforvisit()
        {
            this.usingtariffonabonementforvisit = new HashSet<usingtariffonabonementforvisit>();
        }
    
        public string Name_tariff_on_abonement { get; set; }
        public Nullable<int> Num_days { get; set; }
        public Nullable<int> Max_Num_visits_in_this_tariff { get; set; }
        public decimal Price { get; set; }
    
        public virtual ICollection<usingtariffonabonementforvisit> usingtariffonabonementforvisit { get; set; }
    }
}
