//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkgMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class type_parking
    {
        public type_parking()
        {
            this.parkingzone = new HashSet<parkingzone>();
        }
    
        public long id_type { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<parkingzone> parkingzone { get; set; }
    }
}
