//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkgMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usingtariffonabonementforvisit : ConnectedTariffPlan
    {
        public long id_abonement { get; set; }
        public string Name_tariff_on_abonement { get; set; }
        public int NumOfVisitsMadeWithUsingThisTariff { get; set; }
    
        public virtual tariffonabonementforvisit tariffonabonementforvisit { get; set; }
        public virtual usr usr { get; set; }
    }
}
