//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkgMVC.Models
{
    using System;
    using System.Collections.Generic;
    using ParkgMVC.Models;

    public partial class usr
    {
        public usr()
        {
            this.balance = new HashSet<balance>();
            this.reservation = new HashSet<reservation>();
            this.ts = new HashSet<ts>();
            this.usingtariffonabonementforvisit = new HashSet<usingtariffonabonementforvisit>();
        }
    
        public string Login { get; set; }
        public string FIO { get; set; }
        public Nullable<int> Num_Card_Driver { get; set; }
        public Nullable<decimal> Now_Balance { get; set; }
    
        public virtual ICollection<balance> balance { get; set; }
        public virtual ICollection<reservation> reservation { get; set; }
        public virtual ICollection<ts> ts { get; set; }
        public virtual ICollection<usingtariffonabonementforvisit> usingtariffonabonementforvisit { get; set; }

        MyParkingEntities mp = new MyParkingEntities();

        public void AddUser(string Login)
        {
            usr NewUser = new usr();
            NewUser.Login = Login;
            NewUser.Now_Balance = 0;
            mp.usr.Add(NewUser);
            mp.SaveChanges();
        }
    }
}
