//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkgMVC.Models
{
    using System;
    using System.Collections.Generic;
    using ParkgMVC.Models;

    public partial class visit : Statechart
    {
        public long Num_vis { get; set; }
        public long id_ts { get; set; }
        public long id_location_place { get; set; }
        public string DateIn { get; set; }
        public string DateOut { get; set; }
        public string FirstAttemptGoOut { get; set; }
        public string NextAttemptGoOut { get; set; }
        public long id_vis_param { get; set; }
        
        public virtual place place { get; set; }
        public virtual ts ts { get; set; }
        public virtual visitparameters visitparameters { get; set; }
        MyParkingEntities mp = new MyParkingEntities();

        public bool RegisterIn(long id_loc_place, long id_sts, string Date, long id_vis_param)
        {
            bool Result = true;



            visit vis = new visit();
            vis.id_ts = id_sts;
            vis.id_location_place = id_loc_place;
            vis.DateIn = Date;
            vis.DateOut = "dateout";
            vis.FirstAttemptGoOut = "dateout2";
            vis.NextAttemptGoOut = "dateout3";
            vis.id_vis_param = id_vis_param;
            vis.Status = "Public";
            mp.visit.Add(vis);
            mp.SaveChanges();




            return Result;




        }
    }
}
