//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkgMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class visitparameters : TariffPlan
    {
        public visitparameters()
        {
            this.visit = new HashSet<visit>();
        }
    
        public long id_vis_param { get; set; }
        public int FirstFreeTimeInMinutes { get; set; }
        public int FirstFreeTimeOnChangeBalans { get; set; }

        public virtual ICollection<visit> visit { get; set; }

        public bool AddTariff()
        {
            Status = "ff";
            return true;
        }
    }
}
